---
- name: Install Apache Web Server
  package:
    name: apache2
    state: present

- name: Deploy Apache Configuration
  template:
    src: httpd.conf.j2
    dest: /etc/apache2/apache2.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart Apache

- name: Enable and Start Apache Service
  service:
    name: apache2
    state: started
    enabled: yes
