apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx-app
spec:
  containers:
  - name: nginx
    image: nginx:latest
    command: ["/bin/sh", "-c"]
    args:
      - apt update && apt install -y iputils-ping && nginx -g 'daemon off;';
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 60
