apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  # "myuser" encodé en base64 : echo -n "myuser" | base64 → bXl1c2Vy
  username: bXl1c2Vy
  # "mypassword" encodé en base64 : echo -n "mypassword" | base64 → bXlwYXNzd29yZA==
  password: bXlwYXNzd29yZA==
