apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-app
spec:
  replicas: 3  # Deploy 2 instances of the pod
  selector:
    matchLabels:
      app: nginx-app  # Ensures Deployment manages the right Pods
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        command: ["/bin/sh", "-c"]
        args:
          - apt update && apt install -y iputils-ping  net-tools && nginx -g 'daemon off;';
        resources:
          limits:
            memory: "128Mi"
            cpu: "600m"
        ports:
          - containerPort: 60
        env:
        - name: APP_USERNAME
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: username
        - name: APP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: password
