stages:
  - build
  - test
  - dockerize
  - deploy

build:
  stage: build
  script:
    - echo "Building application..."
  tags:
    - st23-runner

test:
  stage: test
  script:
    - echo "Running tests..."
    - python3 -m venv venv || exit 1
    - source venv/bin/activate || exit 1
    - pip install -r requirements.txt || exit 1
    - python -m unittest discover -s tests -p "test_*.py" || exit 1
  artifacts:
    paths:
      - tests/
  tags:
    - st23-runner

dockerize:
  stage: dockerize
  script:
    - echo "Building Docker image..."
    - docker buildx create --use
    - docker buildx build --load --platform linux/amd64 -t thismann17/st23-repo . || exit 1
    - echo "$DOCKER_PASSWORD" | docker login -u thismann17 --password-stdin || exit 1
    - docker push thismann17/st23-repo || exit 1
  tags:
    - st23-runner


deploy:
  stage: deploy
  before_script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan 10.90.122.235 >> ~/.ssh/known_hosts
  script:
    - echo "Deploying application..."
    - sshpass -p "INNOfuh#" ssh etienne@10.90.122.235 "docker pull thismann17/st23-repo"
    - sshpass -p "INNOfuh#" ssh etienne@10.90.122.235 "docker stop st23-app || true"
    - sshpass -p "INNOfuh#" ssh etienne@10.90.122.235 "docker rm st23-app || true"
    - sshpass -p "INNOfuh#" ssh etienne@10.90.122.235 "docker run -d -p 5000:5000 --name st23-app thismann17/st23-repo"
  tags:
    - st23-runner