- name: Install Vim, Curl and Git
  hosts: all
  become: yes

  tasks:
    - name: update cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Vim, Curl et Git
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - vim
        - curl
        - git
