- name: Install and configure Docker 
  hosts: all
  become: yes

  tasks:
    - name: Install Docker
      ansible.builtin.apt:
        name: docker.io
        state: present

    - name: Start Docker
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: run nginx container
      community.docker.docker_container:
        name: my_nginx
        image: nginx
        state: started
        restart_policy: always