- name: Users management
  hosts: all
  become: yes

  tasks:
    - name: create users
      ansible.builtin.user:
        name: devuser
        groups: sudo
        append: yes

    - name: change permissions on /home/devuser
      ansible.builtin.file:
        path: /home/devuser
        owner: devuser
        group: devuser
        mode: '0755'
