- name: Download WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Extract WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/
    remote_src: yes

- name: Set permissions for WordPress files
  file:
    path: "{{ nginx_root }}"
    owner: www-data
    group: www-data
    mode: "0755"
    recurse: yes

- name: Configure WordPress settings
  template:
    src: wp-config.php.j2
    dest: "{{ nginx_root }}/wp-config.php"
