---
- name: Download latest WordPress archive
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Extract WordPress archive
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: "{{ nginx_root }}"
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Set permissions on WordPress files
  file:
    path: "{{ nginx_root }}"
    state: directory
    owner: www-data
    group: www-data
    recurse: yes

- name: Deploy WordPress configuration file
  template:
    src: wp-config.php.j2
    dest: "{{ nginx_root }}/wp-config.php"
    owner: www-data
    group: www-data
    mode: '0644'
