- name: Install MariaDB
  package:
    name:
      - mariadb-server
      - mariadb-client
    state: present

- name: Start and enable MariaDB
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Secure MariaDB installation
  mysql_user:
    name: root
    password: "{{ wordpress_db_password }}"
    host_all: yes
    login_unix_socket: /var/lib/mysql/mysql.sock
    state: present

- name: Create WordPress database
  mysql_db:
    name: "{{ wordpress_db_name }}"
    state: present

- name: Create WordPress DB user
  mysql_user:
    name: "{{ wordpress_db_user }}"
    password: "{{ wordpress_db_password }}"
    priv: "{{ wordpress_db_name }}.*:ALL"
    state: present
