---
- name: Install PHP-FPM and required PHP modules
  package:
    name:
      - php-fpm
      - php-mysql
      - php-curl
      - php-xml
      - php-mbstring
      - php-gd
    state: present

- name: Deploy PHP-FPM configuration (if needed)
  template:
    src: php.ini.j2
    dest: /etc/php/7.4/fpm/php.ini
  notify: Restart PHP-FPM

- name: Ensure PHP-FPM service is running and enabled
  service:
    name: php7.4-fpm
    state: started
    enabled: yes
