- name: Install Nginx
  package:
    name: nginx
    state: present

- name: Deploy Nginx configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/wordpress
  notify: Restart Nginx

- name: Enable Nginx
  service:
    name: nginx
    state: started
    enabled: yes
